default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  host: localhost
  pool: 30

development:
  <<: *default
  database: helpy_development
  port: 5432
  host: localhost

test:
  <<: *default
  database: helpy_test

production:
  <<: *default
  database: <%= ENV['helpy_DATABASE'] %>
  username: <%= ENV['helpy_DATABASE_USER'] %>
  password: <%= ENV['helpy_DATABASE_PASSWORD'] %>
